# Generated by Django 4.2.16 on 2024-11-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_board',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
