# Generated by Django 4.2.16 on 2024-11-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_notice_board_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice_board',
            name='user',
        ),
    ]
